name: CI

on:
  push:
    branches: [ main, task/introspection ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src/SharpCode

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/SharpCode

    - name: Run unit tests and collect code coverage
      run: >
        dotnet test
        --verbosity diag
        /p:CollectCoverage=true
        /p:Exclude="[*]SharpCode.*Exception"
        /p:CoverletOutput=../../coverage/
        /p:CoverletOutputFormat=cobertura
      working-directory: ./src/SharpCode.Test

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        file: ./coverage/coverage.cobertura.xml
